name: Host Service CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.js"] #js가 변경되면 push

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps: 
    - name: 1. Checkout 
      uses: actions/checkout@v3
    
    - name: 2. Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 3. Build and push 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: kajh7570/hostservice:${{ github.sha }} #docker tags, 자신의 id
  updateYaml: #cd
    runs-on: ubuntu-latest
    needs: buildImage # updateYaml은 biulImage가 끝나야 실행되게 끔 설정
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3
        with:
          repository: "Zlhoon/hostsvc-cd"
          token: ${{ secrets.GITHAB_TOKEN }}
      - name: 2. Change Docker Tag
        run: | 
          sed -i "s/image: kajh7570\/hostservice:.*/image: kajh7570\/hostservice:${{ github.sha }}/g" hostservice-deploy.yaml
          git config --global user.email "kajh7570@gmail.com"
          git config --global user.name "Zlhoon"
          git commit -am "triggered by github action"
          git push origin main
